---
title: "R Notebook"
output: html_notebook
---
```{r}
install.packages(c('tsibble', 'tsibbledata', 'feasts'))
library(tsibble)
library(tsibbledata)
```
##`tsibble`

_index_ : time component 
_key_: identifies the underlying structure of the data 
     : in concojunction with the _index_ uniquelu identifies each individual row


```{r}
vic_elec
```
```{r}
index(vic_elec)
index_var(vic_elec)
```




```{r}
key(vic_elec)
key_vars(vic_elec)


interval(vic_elec)
```
```{r}
library(tidyverse)
vic_elec %>% 
  select(Time, Demand, Temperature)
#if you don't have time it will still be there as time is the index col
```

```{r}
vic_elec %>% 
  filter(!Holiday)
```
```{r}
vic_elec %>% 
  filter(Time < as.POSIXct('2012-01-01 01:00:00', tz = 'Australia/Melbourne'))
```
```{r}
vic_elec %>% 
  filter(Time < as.Date('2012-01-02'))

vic_elec %>% 
  filter_index('2012-01')
```
```{r}
vic_elec <- vic_elec %>% 
  mutate(year = lubridate::year(Date))

vic_elec
```
```{r}
vic_elec %>% 
  select(year, Temperature) %>% 
  group_by(year) %>% 
  summarise(mean_temp = mean(Temperature))
#it still grouped by index didn't work 
```
```{r}
library(lubridate)
vic_elec %>% 
  index_by(as_date(Time)) %>% 
  summarise(mean_temp = mean(Temperature))

vic_elec %>% 
  mutate(time_as_date = as_date(Time), .after = Time)
```
```{r}
vic_elec %>% 
  select(year, Temperature) %>% 
  index_by(year) %>% 
  summarise(mean_temp = mean(Temperature))
#check this with the group by 
```
```{r}
vic_elec %>% 
  filter(!Holiday) %>% 
  ggplot()+
  geom_line(aes(x=Time, y = Temperature))
```
```{r}
elec_date <- vic_elec %>%
  index_by(date = as_date(Time)) %>%
  summarise(temp_mean = mean(Temperature, na.rm = TRUE))

elec_date
```
```{r}
floor_date()
ceiling_date()
yearweek()
yearquarter()
```

```{r}
elec_date %>% 
  ggplot(aes(date, temp_mean))+
  geom_line()
  
```
```{r}
elec_m <- vic_elec %>% 
  index_by(month = month(Time, label = TRUE)) %>% 
  summarise(temp_mean = mean(Temperature, na.rm = TRUE))
elec_m
```

```{r}
elec_m %>% 
  ggplot(aes(month, temp_mean))+
  geom_point()+
  geom_line(group = 1)
#without the group 1 they will join jan to jan but we don't have other jan 
```
```{r}
elec_year <- vic_elec %>%
  index_by(year = year(Time)) %>%
  summarise(temp_mean = mean(Temperature, na.rm = TRUE))


elec_year %>%
  ggplot(aes(x = year, y = temp_mean)) +
  geom_col(fill = "steelblue", alpha = 0.7) + 
  ylab("Mean Temperature")+ 
  xlab("year")
```
```{r}
library(slider)
```

```{r}
elec_rolling <- vic_elec %>% 
  mutate(
    temp_moving_avg = slide_dbl(
      .x = Temperature, 
      .f = ~ mean(., na.rm = TRUE),
      .before = 1000,
      .after = 1000
    )
  )

elec_rolling
```

```{r}
ggplot(elec_rolling) + 
  geom_line(aes(x = Date, y = Temperature), colour = "grey") + 
  geom_line(aes(x = Date, y = temp_moving_avg), colour = "red")
```

```{r}
elec_rolling2 <- vic_elec %>% 
  mutate(
    temp_moving_avg = slide_dbl(
      .x = Temperature, 
      .f = ~ mean(., na.rm = TRUE),
      .before = 100,
      .after = 100,
      .complete = TRUE
    )
  )
elec_rolling2
ggplot(elec_rolling2) + 
  geom_line(aes(x = Date, y = Temperature), colour = "grey") + 
  geom_line(aes(x = Date, y = temp_moving_avg), colour = "red")
```

#feasts

```{r}
tourism

index_var(tourism)
key_vars(tourism)
```
```{r}
tourism %>% 
  distinct(Purpose)

tourism %>% 
  distinct(State, Region, Purpose)

```
```{r}
holidays <- tourism %>% 
  filter(Purpose %in% c('Holiday', 'business')) %>% 
  group_by(State) %>% 
  summarise(Trips = sum(Trips))

holidays
```
```{r}
holidays %>% 
  autoplot(Trips)+
  xlab('Year')
```
```{r}
holidays %>%
  filter(State %in% c("Queensland", "New South Wales", "Victoria")) %>%
  gg_season(Trips)
```
```{r}
holidays %>%
  filter(State %in% c("Queensland", "New South Wales", "Victoria")) %>%
  gg_subseries(Trips)
```

