---
title: "R Notebook"
output: html_notebook
---

# segmentation and clustering 

```{r}
library(tidyverse)
library(cluster)
library(factoextra)
library(dendextend)
library(corrplot)
```


```{r}
edu_data <- read_csv("data2/school_data.csv")
```
```{r}
library(skimr)
```

```{r}
skim(edu_data)
```
```{r}
edu_data<- edu_data %>% 
  column_to_rownames("X1")
edu_data
```


```{r}
edu_data %>% summary()
```

```{r}
edu_data_scale <- edu_data %>% 
  mutate(across(.fns = scale))

skim(edu_data_scale)
```
```{r}
edu_data_scale %>%  cor() %>% 
  corrplot(method = 'number', type = 'lower')
```

calculate distance measure, make a dissimilarity matrix 
```{r}
diss_matrix <- edu_data_scale %>% 
  select(home_school) %>% 
  dist(method = 'euclidean')


```

```{r}
fviz_dist(diss_matrix)
```

```{r}
clusters <- diss_matrix %>% 
  hclust(method = 'complete')

```


```{r}
clusters %>% 
  plot(cex = 0.5,
       hang = -5)
```

```{r}
alt_clusters <- diss_matrix %>% 
  hclust(method = 'ward.D2')
```


```{r}
clustering_dendrogram <- clusters %>% 
  as.dendrogram() %>% 
  dendextend::set('labels_cex', 0.5)
```

```{r}
alt_clustering_dendrogram <- alt_clusters %>% 
  as.dendrogram() %>% 
  dendextend:: set('labels_cex', 0.6)
```

```{r}
dend_diff(clustering_dendrogram, alt_clustering_dendrogram)
```

```{r}
plot(clusters, cex = 0.6, hang = -1)
rect.hclust(clusters, k = 2, border = 2:5)
```
```{r}
edu_clusteres_h6 <- edu_data %>% 
  mutate(school_cluster_group = cutree(clusters, k = 6))

head(edu_clusteres_h6, 20)
```

```{r}
edu_clusteres_h6 %>% 
  group_by(school_cluster_group) %>% 
  summarise(across(.fns = mean))
```


