---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(cluster)
library(factoextra)
library(dendextend)
library(corrplot)
library(janitor)
```


K-means clustering 

```{r}
edu_data <- read_csv('data3/school_data.csv') %>% column_to_rownames('X1') %>% janitor::clean_names()
```

```{r}
edu_data<- edu_data %>% 
  select(home_school:state_school)
```

```{r}
edu_data %>% 
  ggplot(aes(x = home_school,
             y = state_school))+
  geom_point()
```

```{r}
edu_scale <- edu_data %>% 
   mutate(across(.fns = scale))
edu_scale
```

```{r}
set.seed(1234)

clustered_edu <- edu_scale %>% 
  kmeans(centers = 6,
         nstart = 25)

clustered_edu
```
```{r}
library(broom)

tidy(clustered_edu, 
     col.names = colnames(edu_scale))
```
```{r}
clustered_edu %>% 
  augment(edu_data)
```


```{r}
glance(clustered_edu)
```
```{r}
# set min& max of clusters
max_k <- 20
k_clusters <- tibble(k = 1:max_k) %>% 
  mutate(
    kclust = map(k, ~ kmeans(edu_scale, .x, nstart = 25)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, edu_data)
  )

k_clusters
```

```{r}
clusterings <- k_clusters %>% 
  unnest(glanced)

clusterings
```

```{r}
clusterings %>% 
  ggplot(aes(x = k,
             y = tot.withinss))+
  geom_point()+
  geom_line()+
  scale_x_continuous(breaks = seq(1,20,1))
```
```{r}
library(factoextra)
```

```{r}
fviz_nbclust(edu_scale,
             kmeans,
             method = "wss",
             nstart = 25)
```
```{r}
fviz_nbclust(edu_scale, 
             kmeans, 
             method = "silhouette", 
             nstart = 25)
```

```{r}
fviz_nbclust(edu_scale, 
             kmeans, 
             method = "gap_stat", 
             nstart = 25, 
             k.max = 10)
```
```{r}
 clusterings %>% 
  unnest(cols = c(augmented)) %>%
  filter(k <= 6) %>%
  ggplot(aes(x = home_school, y = state_school)) +
  geom_point(aes(color = .cluster))+
  facet_grid(.~k)
```








