---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(janitor)
```

```{r}
telco <- read_csv("data/telecomms_churn.csv") %>% clean_names()
```
```{r}
glimpse(telco)
```

this 7043 represent the whole population 
we can calculate the population paramaters, we can' normally do that 
```{r}
summary_popn <- telco %>% 
  summarise(
    mean_monthly = mean(monthly_charges),
    mean_tenure = mean(tenure),
    prop_churn = sum(churn == 'Yes')/n()
  )
summary_popn
```
```{r}
telco %>%
  ggplot(aes(x = monthly_charges)) + 
  geom_histogram(col = "white", fill = "steel blue", alpha = 0.7)
```
```{r}
telco %>%
  ggplot(aes(x = tenure)) + 
  geom_histogram(col = "white", fill = "steel blue", alpha = 0.7)
```

```{r}
telco %>%
  ggplot(aes(x = churn)) + 
  geom_bar(col = "white", fill = "steel blue", alpha = 0.7)
```
```{r}
library(infer)
```
this package helps to get samples 
let's start taking random samples 
rep_sample_n
```{r}
sample_200 <- telco %>%
  rep_sample_n(size = 200, reps = 1)

sample_200
```


```{r}
groups(sample_200)
```
```{r}
summary_sample_200 <- sample_200 %>% 
  ungroup() %>% 
   summarise(
    mean_monthly = mean(monthly_charges),
    mean_tenure = mean(tenure),
    prop_churn = sum(churn == 'Yes')/n()
  )
summary_sample_200
```

```{r}
summary_sample_200 - summary_popn
```
```{r}
rep_sample_200 <- telco %>%
  rep_sample_n(size = 200, reps = 5000) %>% 
   summarise(
    mean_monthly = mean(monthly_charges),
    mean_tenure = mean(tenure),
    prop_churn = sum(churn == 'Yes')/n()
  )
#5000 of 200 sized samples 
rep_sample_200 
```


```{r}
monthly_charges_plot <- rep_sample_200 %>%
  ggplot(aes(x = mean_monthly)) + 
  geom_histogram(col = "white", fill = "steel blue", alpha = 0.7) +
  labs(x = "mean monthly_charges from each sample")

monthly_charges_plot
```

```{r}
tenure_plot <- rep_sample_200 %>%
  ggplot(aes(x = mean_tenure)) +
  geom_histogram(col = "white", fill = "steel blue", alpha = 0.7)
tenure_plot
```
```{r}
churn_plot <- rep_sample_200 %>%
  ggplot(aes(x = prop_churn)) +
  geom_histogram(col = "white", fill = "steel blue", alpha = 0.7, binwidth = 0.01) 
churn_plot
```
```{r}
std_errs <- rep_sample_200 %>%
  summarise(
    se_mean_monthly = sd(mean_monthly),
    se_mean_tenure = sd(mean_tenure),
    se_prop_churn = sd(prop_churn)
  )
std_errs
```
```{r}
library(fastGraph)
```

```{r}
shadeDist(
  xshade = c(60, 70), 
  lower.tail = FALSE, 
  ddist = "dnorm", 
  parm1 = mean(rep_sample_200$mean_monthly), 
  parm2 = std_errs$se_mean_monthly, 
  xlab = "mean_monthly_charges"
)
```
```{r}
rep_sample_200 %>%
  filter(mean_monthly >= 60, mean_monthly<= 70) %>%
  summarise(prob = n() / nrow(rep_sample_200))
```








